package net.ivanzykov.craftworkstasktracker;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.time.OffsetDateTime;

/**
 * Entity of a task.
 */
@Entity
@Table(name = "tasks")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Task {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "created_at")
    @CreationTimestamp
    private OffsetDateTime createdAt;

    @Column(name = "updated_at")
    @UpdateTimestamp
    private OffsetDateTime updatedAt;

    @Column(name = "due_date")
    @NotNull
    private OffsetDateTime dueDate;

    @Column(name = "resolved_at")
    private OffsetDateTime resolvedAt;

    @NotNull
    private String title;
    private String description;
    @NotNull
    private String priority;
    @NotNull
    private String status;

    protected Task() {}

    /**
     * Public constructor for a Task entity with all fields as arguments.
     *
     * @param createdAt     date with a datestamp when object of this entity was created
     * @param updatedAt     date with a datestamp when object of this entity was last updated
     * @param dueDate       date with a date of the deadline date for this task
     * @param resolvedAt    date with a date when this task was finished
     * @param title         string with the title
     * @param description   string with description
     * @param priority      string with a four-character priority code (e.g. wait/work/done)
     * @param status        string with a two-character status code (e.g. hi/md/lo)
     */
    public Task(OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime dueDate, OffsetDateTime resolvedAt,
                String title, String description, String priority, String status) {
        // TODO: is this field needed? It is auto-generated by the DB
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.dueDate = dueDate;
        this.resolvedAt = resolvedAt;
        this.title = title;
        this.description = description;
        this.priority = priority;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public OffsetDateTime getDueDate() {
        return dueDate;
    }

    public void setDueDate(OffsetDateTime dueDate) {
        this.dueDate = dueDate;
    }

    public OffsetDateTime getResolvedAt() {
        return resolvedAt;
    }

    public void setResolvedAt(OffsetDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
